spring:
    application.name: tariff_manager
    datasource:
        url: jdbc:h2:mem:inditexdb
        driverClassName: org.h2.Driver
        username: ${DB_USERNAME:sa}
        password: ${DB_PASSWORD:password}

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        packages-to-scan: com.inditex.tariff_manager.shared.persistence.h2

springdoc:
    swagger-ui:
        url: /swagger.yaml